owner: whiteravens20
repo: status.wrservices.link

sites:
  - name: White Ravens Home
    url: https://whiteravens.net
  - name: Dokumentacja WR
    url: https://wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/documentation/favicon-96x96.png
  - name: Dashboard
    url: https://home.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/dashboard/favicon-96x96.png
  - name: Metawyszukiwarka
    url: https://search.whiteravens.net
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/search/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Element Web
    url: https://chat.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/element/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Udostępnianie plików
    url: https://fileshare.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/fileshare/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Pastebin
    url: https://pastebin.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/pastebin/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Instancja Invidious
    url: https://invid.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/invid/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Synapse
    url: $SYNAPSE_URL
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/synapse/favicon-96x96.png
    assignees:
      - pavlojs
  - name: System Powiadomień
    url: $NOTIFY_URL
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/notify/favicon-96x96.png
    assignees:
      - pavlojs

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wrservices.link
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | White Ravens Services
  introTitle: "Status usług **White Ravens**"
  introMessage: "Ta strona prezentuje bieżące statusy usług i aplikacji **White Ravens**. Monitorujemy dostępność i działanie systemów w czasie rzeczywistym, publikując informacje o wszelkich incydentach i przerwach w działaniu."
  navbar:
    - title: Status
      href: /
    - title: White Ravens Home
      href: https://whiteravens.net
    - title: Dokumentacja
      href: https://wrservices.link
    - title: GitHub
      href: https://github.com/whiteravens20/status.wrservices.link

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration