owner: whiteravens20
repo: status.wrservices.link

sites:
  - name: White Ravens Home
    url: https://whiteravens.net
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/homepage/favicon-96x96.png
  - name: Dokumentacja WR
    url: https://wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/documentation/favicon-96x96.png
  - name: Dashboard
    url: https://home.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/dashboard/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Metawyszukiwarka
    url: https://search.whiteravens.net
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/search/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Element Web
    url: https://chat.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/element/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Udostępnianie plików
    url: https://fileshare.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/fileshare/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Pastebin
    url: https://pastebin.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/pastebin/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Instancja Invidious
    url: https://invid.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/invid/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Habitica
    url: https://habitica.wrservices.link
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/habitica/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Chmura WR
    url: $CLOUD_URL
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/cloud/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Synapse
    url: $SYNAPSE_URL
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/synapse/favicon-96x96.png
    assignees:
      - pavlojs
  - name: Integrator Office
    url: $OFFICE_URL
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/office/favicon-96x96.png
    assignees:
      - pavlojs
  - name: System Powiadomień
    url: $NOTIFY_URL
    icon: https://raw.githubusercontent.com/whiteravens20/services-images/refs/heads/main/full-assets/notify/favicon-96x96.png
    assignees:
      - pavlojs

status-website:
  robotsText: "User-agent: * \n Disallow: /"
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.wrservices.link
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Status | White Ravens Services
  introTitle: "Status usług **White Ravens**"
  introMessage: "Ta strona prezentuje bieżące statusy usług i aplikacji **White Ravens**. Monitorujemy dostępność i działanie systemów w czasie rzeczywistym, publikując informacje o wszelkich incydentach i przerwach w działaniu."
  navbar:
    - title: Status
      href: /
    - title: White Ravens Home
      href: https://whiteravens.net
    - title: Dokumentacja
      href: https://wrservices.link
    - title: GitHub
      href: https://github.com/whiteravens20/status.wrservices.link

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration

# Localisation - polish
i18n:
  url: "URL"
  status: "Status"
  history: "Historia"
  responseTime: "Czas odpowiedzi"
  uptime: "Dostępność"
  up: "🟩 Działa"
  degraded: "🟨 Ograniczona wydajność"
  down: "🟥 Nie działa"
  responseTimeGraphAlt: "Wykres czasu odpowiedzi"
  ms: "ms"
  responseTimeDay: "Czas odpowiedzi (24h)"
  responseTimeWeek: "Czas odpowiedzi (7 dni)"
  responseTimeMonth: "Czas odpowiedzi (30 dni)"
  responseTimeYear: "Czas odpowiedzi (1 rok)"
  uptimeDay: "Dostępność (24h)"
  uptimeWeek: "Dostępność (7 dni)"
  uptimeMonth: "Dostępność (30 dni)"
  uptimeYear: "Dostępność (1 rok)"
  overallUptime: "Całkowita dostępność: $UPTIME"
  overallUptimeTitle: "Całkowita dostępność"
  averageResponseTime: "Średni czas odpowiedzi: $TIMEms"
  averageResponseTimeTitle: "Średni czas odpowiedzi"
  sevelDayResponseTime: "Czas odpowiedzi z ostatnich 7 dni"
  responseTimeMs: "Czas odpowiedzi (ms)"
  liveStatus: "Status na żywo"
  liveStatusHtmlComment: "<!--status na żywo-->"
  allSystemsOperational: "Wszystkie systemy działają poprawnie"
  degradedPerformance: "🟨 Ograniczona wydajność"
  completeOutage: "🟥 Całkowita awaria"
  partialOutage: "🟧 Częściowa awaria"
  activeIncidents: "Aktywne incydenty"
  incidentReport: "Raport incydentu #$NUMBER →"
  activeIncidentSummary: "Otwarto $DATE z $POSTS wpisami"
  incidentTitle: "Szczegóły incydentu $NUMBER"
  incidentDetails: "Szczegóły incydentu"
  incidentFixed: "Naprawiono"
  incidentOngoing: "W toku"
  incidentOpenedAt: "Otwarto o"
  incidentClosedAt: "Zamknięto o"
  incidentViewOnGitHub: "Zobacz i subskrybuj na GitHub"
  incidentCommentSummary: "Opublikowano $DATE przez $AUTHOR"
  incidentBack: "← Powrót do wszystkich incydentów"
  pastIncidents: "Przeszłe incydenty"
  pastIncidentsResolved: "Rozwiązano w $MINUTES minut z $POSTS wpisami"
  pastScheduledMaintenance: "Przeszłe zaplanowane prace konserwacyjne"
  scheduledMaintenance: "Zaplanowane prace konserwacyjne"
  scheduledMaintenanceSummaryStarted: "Rozpoczęto $DATE na $DURATION minut"
  scheduledMaintenanceSummaryStarts: "Rozpocznie się $DATE na $DURATION minut"
  startedAt: "Rozpoczęto o"
  startsAt: "Rozpoczyna się o"
  duration: "Czas trwania"
  durationMin: "$DURATION minut"
  incidentCompleted: "Zakończone"
  incidentScheduled: "Zaplanowane"
  duration24H: "24h"
  duration7D: "7d"
  duration30D: "30d"
  duration1Y: "1r"
  durationAll: "wszystko"
  loading: "Ładowanie"
  navGitHub: "GitHub"
  footer: "White Ravens 2.0. Ta strona jest [open source]($REPO), działa dzięki [Upptime](https://upptime.js.org)"
  rateLimitExceededTitle: "Przekroczony limit żądań"
  rateLimitExceededIntro: "Przekroczyłeś liczbę dozwolonych żądań na godzinę, więc musisz poczekać, zanim ponownie uzyskasz dostęp do tej strony. Alternatywnie możesz dodać osobisty token dostępu GitHub, aby kontynuować korzystanie z tej strony."
  rateLimitExceededWhatDoesErrorMean: "Co oznacza ten błąd?"
  rateLimitExceededErrorMeaning: "Ta strona korzysta z API GitHub do pobierania danych na temat statusu naszych stron w czasie rzeczywistym. Domyślnie GitHub pozwala na 60 żądań na godzinę dla każdego adresu IP, które zostały przez Ciebie wykorzystane."
  rateLimitExceededErrorHowCanFix: "Jak mogę to naprawić?"
  rateLimitExceededErrorFix: "Możesz poczekać godzinę, a limit Twojego adresu IP zostanie przywrócony. Alternatywnie możesz dodać swój osobisty token dostępu GitHub, który zwiększy limit do 5000 żądań na godzinę."
  rateLimitExceededGeneratePAT: "Dowiedz się, jak wygenerować osobisty token dostępu"
  rateLimitExceededHasSet: "Masz ustawiony osobisty token dostępu."
  rateLimitExceededRemoveToken: "Usuń token"
  rateLimitExceededGitHubPAT: "Osobisty token dostępu GitHub"
  rateLimitExceededCopyPastePAT: "Skopiuj i wklej swój token"
  rateLimitExceededSaveToken: "Zapisz token"
  errorTitle: "Wystąpił błąd"
  errorIntro: "Wystąpił błąd podczas próby pobrania najnowszych informacji o statusie."
  errorText: "Możesz spróbować ponownie za kilka chwil."
  errorHome: "Przejdź na stronę główną"
  locale: "pl-PL"